


os: linux
sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

before_install:

script:
 #gcc -Wall main.cpp -o test.out
 #- cmake .
 #- cmake --build .
 mkdir build
 cd build
 cmake ..
 make

after_install:
 - .test.out
 

script:

 